name: Release

on:
  workflow_dispatch:
    inputs:
      version-level:
        description: 'Version level to bump'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cut tag
        id: cut-tag
        uses: ./
        with:
          version-level: ${{ inputs.version-level }}

      - name: Output results
        run: |
          echo "New version: ${{ steps.cut-tag.outputs.version }}"
          echo "Created tag: ${{ steps.cut-tag.outputs.tag }}"